const heroes = [
  // 🟣 Mythic+ (Bleed Rotation)
  { name: "Superman", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Joker", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Scarecrow", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Deathstroke", rarity: "Mythic+", isInBleed: true, bleedDaysLeft: 15 },
  { name: "Sinestro", rarity: "Mythic+", isInBleed: true, bleedDaysLeft: 30 },
  { name: "Zatanna", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Constantine", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Hawkgirl", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Nightwing", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },
  { name: "Martian Manhunter", rarity: "Mythic+", isInBleed: false, bleedDaysLeft: 0 },

  // 🔵 Mythic
  { name: "Green Lantern", rarity: "Mythic", isInBleed: false },
  { name: "Harley Quinn", rarity: "Mythic", isInBleed: false },
  { name: "Batman", rarity: "Mythic", isInBleed: false },
  { name: "Dr. Fate", rarity: "Mythic", isInBleed: false },
  { name: "Raven", rarity: "Mythic", isInBleed: false },
  { name: "Aquaman", rarity: "Mythic", isInBleed: false },

  // 🟠 Legendary
  { name: "Wonder Woman", rarity: "Legendary", isInBleed: false },
  { name: "Poison Ivy", rarity: "Legendary", isInBleed: false },
  { name: "Mera", rarity: "Legendary", isInBleed: false },
  { name: "Green Arrow", rarity: "Legendary", isInBleed: false },
  { name: "Black Adam", rarity: "Legendary", isInBleed: false },
  { name: "Two-Face", rarity: "Legendary", isInBleed: false },
  { name: "Cyborg", rarity: "Legendary", isInBleed: false },
  { name: "Shazam", rarity: "Legendary", isInBleed: false },
  { name: "Robin", rarity: "Legendary", isInBleed: false },
  { name: "Red Hood", rarity: "Legendary", isInBleed: false },
  { name: "Lex Luthor", rarity: "Legendary", isInBleed: false },
  { name: "Batgirl", rarity: "Legendary", isInBleed: false },
  { name: "The Flash", rarity: "Legendary", isInBleed: false },
  { name: "Vixen", rarity: "Legendary", isInBleed: false },
  { name: "Penguin", rarity: "Legendary", isInBleed: false },
  { name: "Killer Croc", rarity: "Legendary", isInBleed: false },
  { name: "Captain Cold", rarity: "Legendary", isInBleed: false },
  { name: "Deadshot", rarity: "Legendary", isInBleed: false },
  { name: "Bane", rarity: "Legendary", isInBleed: false },
  { name: "Red Robin", rarity: "Legendary", isInBleed: false },
  { name: "Star Girl", rarity: "Legendary", isInBleed: false },
  { name: "Black Canary", rarity: "Legendary", isInBleed: false },
  { name: "Catwoman", rarity: "Legendary", isInBleed: false },
  { name: "Atom", rarity: "Legendary", isInBleed: false },
];
